In [3]:
import pandas as pd
import numpy as np

# Open CSV

In [4]:
dfRating=pd.read_csv('rating.csv')
dfRating=dfRating
dfRating.head()

   user_id  anime_id  rating
0        1        20      -1
1        1        24      -1
2        1        79      -1
3        1       226      -1
4        1       241      -1

# Pivot Table

In [5]:
dfPivot=dfRating.pivot_table(
    index=['user_id'],columns=['anime_id'],values='rating'
)
dfPivot=dfPivot.fillna(0)
dfPivot.head()

anime_id,1,5,6,7,8,15,16,17,18,19,...,34283,34324,34325,34349,34358,34367,34412,34475,34476,34519
user_id,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,8.0,0.0,0.0,6.0,0.0,6.0,6.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# CorrMatrix

In [ ]:
corrMatrix=dfPivot.corr()
corrMatrix.head()

# Save Corr Matrix to Pickle

In [5]:
import pickle
with open('corrMatrix.pkl','rb') as x:
        corrMatrix=pickle.load(x)

In [6]:
corrMatrix=corrMatrix.set_index('anime_id')
corrMatrix.head()

In [30]:
userX=[(91,5),(1,5),(48,4),(1,3)]
finalSkor=pd.DataFrame()
for anime_id,rating in userX:
    skor=corrMatrix.loc[anime_id]*rating
    skor=skor.sort_values(ascending=False)
    finalSkor=finalSkor.append(skor)
finalSkor=finalSkor.sum().sort_values(ascending=False)
finalSkor[:15].index.values
final=finalSkor[:8].index.values
final

array(['1', '91', '48', '5', '6', '90', '205', '227'], dtype=object)

In [12]:
data=pd.read_csv('AnimeUpdatedImage.csv')
data.head()

,Unnamed: 0,animeID,name,title_english,title_japanese,title_synonyms,type,source,producers,genre,...,rank,popularity,members,favorites,synopsis,background,premiered,broadcast,related,image_url
0,0,1,Cowboy Bebop,Cowboy Bebop,カウボーイビバップ,[],TV,Original,['Bandai Visual'],"['Action', 'Adventure', 'Comedy', 'Drama', 'Sc...",...,26.0,39.0,795733.0,43460.0,"In the year 2071, humanity has colonized sever...",When Cowboy Bebop first aired in spring of 199...,Spring 1998,Saturdays at 01:00 (JST),"{'Adaptation': [{'mal_id': 173, 'type': 'manga...",['https://cdn.myanimelist.net/images/anime/4/1...
1,1,5,Cowboy Bebop: Tengoku no Tobira,Cowboy Bebop: The Movie,カウボーイビバップ 天国の扉,"[""Cowboy Bebop: Knockin' on Heaven's Door""]",Movie,Original,"['Sunrise', 'Bandai Visual']","['Action', 'Drama', 'Mystery', 'Sci-Fi', 'Space']",...,164.0,449.0,197791.0,776.0,"Another day, another bounty—such is the life o...",NaN,NaN,NaN,"{'Parent story': [{'mal_id': 1, 'type': 'anime...",['https://cdn.myanimelist.net/images/anime/6/1...
2,2,6,Trigun,Trigun,トライガン,[],TV,Manga,['Victor Entertainment'],"['Action', 'Sci-Fi', 'Adventure', 'Comedy', 'D...",...,255.0,146.0,408548.0,10432.0,"Vash the Stampede is the man with a $$60,000,0...",The Japanese release by Victor Entertainment h...,Spring 1998,Thursdays at 01:15 (JST),"{'Adaptation': [{'mal_id': 703, 'type': 'manga...",['https://cdn.myanimelist.net/images/anime/7/2...
3,3,7,Witch Hunter Robin,Witch Hunter Robin,Witch Hunter ROBIN,['WHR'],TV,Original,['Bandai Visual'],"['Action', 'Magic', 'Police', 'Supernatural', ...",...,2371.0,1171.0,79397.0,537.0,Witches are individuals with special powers li...,NaN,Summer 2002,Tuesdays at Unknown,{},['https://cdn.myanimelist.net/images/anime/179...
4,4,8,Bouken Ou Beet,Beet the Vandel Buster,冒険王ビィト,['Adventure King Beet'],TV,Manga,"['TV Tokyo', 'Dentsu']","['Adventure', 'Fantasy', 'Shounen', 'Supernatu...",...,3544.0,3704.0,11708.0,14.0,It is the dark century and the people are suff...,NaN,Fall 2004,Thursdays at 18:30 (JST),"{'Adaptation': [{'mal_id': 1348, 'type': 'mang...",['https://cdn.myanimelist.net/images/anime/7/2...

# Test Output

In [33]:
rekomen=[]
for item in final:
    x=data[data['animeID']==int(item)][' name']
    rekomen.append(list(x)[0])
rekomen
#     rekomen.append(list(x))
# for item in rekomen:
#     print( item)

['Cowboy Bebop',
 'Mobile Suit Gundam Wing: Endless Waltz',
 '.hack//Sign',
 'Cowboy Bebop: Tengoku no Tobira',
 'Trigun',
 'Mobile Suit Gundam Wing',
 'Samurai Champloo',
 'FLCL']